from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    ENV: str = "dev"

    SUPABASE_URL: str
    SUPABASE_ANON_KEY: str
    SUPABASE_SERVICE_ROLE_KEY: str

    FREE_DAILY_AI_LIMIT: int = 10
    LLM_API_KEY: str = ""

    DEEPSEEK_API_KEY: str = ""
    DEEPSEEK_BASE_URL: str = "https://api.deepseek.com"
    DEEPSEEK_MODEL: str = "deepseek-chat"
    DEEPSEEK_REASONER_MODEL: str = "deepseek-reasoner"

    TAVILY_API_KEY: str = ""
    RESEARCH_MAX_SOURCES: int = 15
    RESEARCH_MAX_STEPS: int = 4

    STRIPE_SECRET_KEY: str = ""
    STRIPE_WEBHOOK_SECRET: str = ""
    STRIPE_PUBLISHABLE_KEY: str = ""
    STRIPE_PRICE_PRO_MONTHLY: str = ""
    STRIPE_PRICE_PRO_YEARLY: str = ""
    STRIPE_PRICE_PREMIUM_MONTHLY: str = ""
    STRIPE_PRICE_PREMIUM_YEARLY: str = ""

    MPESA_CONSUMER_KEY: str = ""
    MPESA_CONSUMER_SECRET: str = ""
    MPESA_SHORTCODE: str = ""
    MPESA_PASSKEY: str = ""
    MPESA_CALLBACK_URL: str = ""
    MPESA_ENVIRONMENT: str = "sandbox"

    APP_BASE_URL: str = "http://localhost:3000"
    BACKEND_BASE_URL: str = "http://localhost:8000"
    CORS_ORIGINS: str = "http://localhost:3000,http://127.0.0.1:3000"

    model_config = SettingsConfigDict(env_file=".env")


settings = Settings()

SUPABASE_URL = settings.SUPABASE_URL
SUPABASE_ANON_KEY = settings.SUPABASE_ANON_KEY
SUPABASE_SERVICE_ROLE_KEY = settings.SUPABASE_SERVICE_ROLE_KEY
FREE_DAILY_AI_LIMIT = settings.FREE_DAILY_AI_LIMIT
LLM_API_KEY = settings.LLM_API_KEY
DEEPSEEK_API_KEY = settings.DEEPSEEK_API_KEY
DEEPSEEK_BASE_URL = settings.DEEPSEEK_BASE_URL
DEEPSEEK_MODEL = settings.DEEPSEEK_MODEL
DEEPSEEK_REASONER_MODEL = settings.DEEPSEEK_REASONER_MODEL
TAVILY_API_KEY = settings.TAVILY_API_KEY
RESEARCH_MAX_SOURCES = settings.RESEARCH_MAX_SOURCES
RESEARCH_MAX_STEPS = settings.RESEARCH_MAX_STEPS
STRIPE_SECRET_KEY = settings.STRIPE_SECRET_KEY
STRIPE_WEBHOOK_SECRET = settings.STRIPE_WEBHOOK_SECRET
STRIPE_PUBLISHABLE_KEY = settings.STRIPE_PUBLISHABLE_KEY
STRIPE_PRICE_PRO_MONTHLY = settings.STRIPE_PRICE_PRO_MONTHLY
STRIPE_PRICE_PRO_YEARLY = settings.STRIPE_PRICE_PRO_YEARLY
STRIPE_PRICE_PREMIUM_MONTHLY = settings.STRIPE_PRICE_PREMIUM_MONTHLY
STRIPE_PRICE_PREMIUM_YEARLY = settings.STRIPE_PRICE_PREMIUM_YEARLY
MPESA_CONSUMER_KEY = settings.MPESA_CONSUMER_KEY
MPESA_CONSUMER_SECRET = settings.MPESA_CONSUMER_SECRET
MPESA_SHORTCODE = settings.MPESA_SHORTCODE
MPESA_PASSKEY = settings.MPESA_PASSKEY
MPESA_CALLBACK_URL = settings.MPESA_CALLBACK_URL
MPESA_ENVIRONMENT = settings.MPESA_ENVIRONMENT
APP_BASE_URL = settings.APP_BASE_URL
BACKEND_BASE_URL = settings.BACKEND_BASE_URL
CORS_ORIGINS = settings.CORS_ORIGINS
ENV = settings.ENV
